<?php

declare(strict_types=1);

namespace VoltCMS\MCP\OAuth\Keys;

use League\OAuth2\Server\CryptKey;
use VoltCMS\MCP\Configuration;
use VoltCMS\UserAccess\Utils;

/**
 * Generation, storage and rotation of the RS256 keypair every access token is signed with.
 *
 * This is real work the opaque-token design would have avoided, and it exists here so no consuming
 * application has to get it right. A blog on shared hosting has no key management story: without
 * this it would either commit a key to version control, leave one world-readable under the web
 * root, or never rotate at all.
 *
 * ## Rotation, and why the old public key sticks around
 *
 * Access tokens are self-contained and live an hour. Rotating the signing key does not invalidate
 * them — they were signed by the previous key and remain perfectly valid until they expire — so a
 * rotation that deleted the old public key would reject every live token and log every client out.
 * `rotate()` therefore keeps the RETIRED PUBLIC key, in `retired/`, until the last token it could
 * have signed has expired, and drops it after. The retired PRIVATE key is not kept: nothing signs
 * with it again, so holding on to it would be a liability with no use.
 *
 * Rotation is deliberately manual. A flat-file deployment has no daemon, so there is nothing to run
 * a schedule; the README shows the cron line for deployments that want one. See
 * docs/decisions/0004-key-rotation.md.
 */
final class KeyManager
{
    // --- Failure codes ---

    public const EXCEPTION_GENERATION_FAILED    = 8001;
    public const EXCEPTION_KEY_UNREADABLE       = 8002;
    public const EXCEPTION_DIRECTORY_UNWRITABLE = 8003;
    public const EXCEPTION_KEY_MALFORMED        = 8004;

    // --- Policy ---

    public const KEY_BITS = 2048;

    /** Owner read/write only. A signing key any other account on the host can read is not a secret. */
    public const PRIVATE_KEY_MODE = 0600;

    public const PUBLIC_KEY_MODE = 0644;

    /** Clock skew allowance on top of the access token TTL, so a rotation never clips a live token. */
    public const RETIREMENT_GRACE_SECONDS = 300;

    private const RETIRED_DIRECTORY = 'retired';
    private const RETIRED_SUFFIX    = '.pub';

    public function __construct(private readonly Configuration $configuration)
    {
    }

    // --- Generation ---

    /**
     * Generate the keypair if it is not there yet. Safe to call on every request: it does nothing
     * once the files exist, which is what lets a consuming application call it from its bootstrap
     * rather than needing an install step.
     *
     * @return bool True if a keypair was generated by this call.
     */
    public function ensureKeyPair(): bool
    {
        if (is_file($this->configuration->privateKeyPath) && is_file($this->configuration->publicKeyPath)) {
            return false;
        }

        [$private, $public] = $this->generate();

        $this->writePrivateKey($private);
        $this->writePublicKey($public);

        return true;
    }

    /**
     * Replace the signing key, keeping the outgoing public key until the tokens it signed expire.
     *
     * @return string The new key's identifier.
     */
    public function rotate(?\DateTimeImmutable $now = null): string
    {
        $now = $now ?? new \DateTimeImmutable();

        if (is_file($this->configuration->publicKeyPath)) {
            $this->retire($this->publicKeyPem(), $now);
        }

        [$private, $public] = $this->generate();

        $this->writePrivateKey($private);
        $this->writePublicKey($public);
        $this->purgeRetiredKeys($now);

        return self::thumbprint($public);
    }

    // --- Reads ---

    public function privateKey(): CryptKey
    {
        $this->ensureKeyPair();

        return new CryptKey('file://' . $this->configuration->privateKeyPath, null, false);
    }

    public function publicKeyPem(): string
    {
        $this->ensureKeyPair();

        return $this->read($this->configuration->publicKeyPath);
    }

    /** The `kid` of the key currently signing, as an RFC 7638 JWK thumbprint. */
    public function keyId(): string
    {
        return self::thumbprint($this->publicKeyPem());
    }

    /**
     * Every public key a live token might have been signed by: the current one first, then any
     * retired key still inside its grace window.
     *
     * @return list<string>
     */
    public function verificationKeys(): array
    {
        $keys = [$this->publicKeyPem()];

        foreach ($this->retiredKeys() as $pem) {
            $keys[] = $pem;
        }

        return $keys;
    }

    /**
     * The JWKS document, in the shape `mcp/sdk`'s `JwksProvider` and every other RFC 7517 consumer
     * expects. Public material only — there is nothing here that is not already on the wire in
     * every token's signature.
     *
     * @return array{keys: list<array<string, string>>}
     */
    public function jwks(): array
    {
        $keys = [];

        foreach ($this->verificationKeys() as $pem) {
            $keys[] = self::jwk($pem);
        }

        return ['keys' => $keys];
    }

    // --- Retirement ---

    /**
     * Delete retired keys whose grace window has closed.
     *
     * @return int Number of keys deleted.
     */
    public function purgeRetiredKeys(?\DateTimeImmutable $now = null): int
    {
        $cutoff  = ($now ?? new \DateTimeImmutable())->getTimestamp();
        $deleted = 0;

        foreach ($this->retiredKeyPaths() as $path => $expiry) {
            if ($expiry <= $cutoff) {
                @unlink($path);
                $deleted++;
            }
        }

        return $deleted;
    }

    /**
     * @return list<string> PEM-encoded public keys still inside their grace window.
     */
    private function retiredKeys(): array
    {
        $now  = time();
        $keys = [];

        foreach ($this->retiredKeyPaths() as $path => $expiry) {
            if ($expiry > $now) {
                $keys[] = $this->read($path);
            }
        }

        return $keys;
    }

    /**
     * Keyed by path, not by expiry: two rotations inside the same second produce the same expiry,
     * and keying by it would silently drop one of the two retired keys — along with every token it
     * had signed.
     *
     * @return array<string, int> Path => expiry timestamp.
     */
    private function retiredKeyPaths(): array
    {
        $paths = glob($this->retiredDirectory() . DIRECTORY_SEPARATOR . '*' . self::RETIRED_SUFFIX);
        $found = [];

        foreach ($paths === false ? [] : $paths as $path) {
            if (preg_match('/^(\d{1,12})-/', basename($path), $matches) === 1) {
                $found[$path] = (int) $matches[1];
            }
        }

        return $found;
    }

    private function retire(string $publicKeyPem, \DateTimeImmutable $now): void
    {
        $expiry = $now->add($this->configuration->accessTokenTtl)->getTimestamp() + self::RETIREMENT_GRACE_SECONDS;
        $name   = $expiry . '-' . substr(hash('sha256', $publicKeyPem), 0, 16) . self::RETIRED_SUFFIX;

        $this->writeFile(
            $this->retiredDirectory() . DIRECTORY_SEPARATOR . $name,
            $publicKeyPem,
            self::PUBLIC_KEY_MODE,
        );
    }

    private function retiredDirectory(): string
    {
        return dirname($this->configuration->privateKeyPath) . DIRECTORY_SEPARATOR . self::RETIRED_DIRECTORY;
    }

    // --- JWK ---

    /**
     * RFC 7638 §3: the thumbprint is the SHA-256 of the JWK's required members, in lexicographic
     * order, with no whitespace. Deriving `kid` rather than inventing one means a key has the same
     * identifier wherever it is published, and a rotation cannot accidentally reuse the last one.
     */
    public static function thumbprint(string $publicKeyPem): string
    {
        $jwk = self::jwk($publicKeyPem);

        $canonical = json_encode(
            ['e' => $jwk['e'], 'kty' => $jwk['kty'], 'n' => $jwk['n']],
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES,
        );

        return self::base64UrlEncode(hash('sha256', $canonical, true));
    }

    /**
     * @return array<string, string>
     */
    private static function jwk(string $publicKeyPem): array
    {
        $key     = openssl_pkey_get_public($publicKeyPem);
        $details = $key === false ? false : openssl_pkey_get_details($key);

        if ($details === false || !isset($details['rsa']['n'], $details['rsa']['e'])) {
            throw new \RuntimeException('The public key is not an RSA key.', self::EXCEPTION_KEY_MALFORMED);
        }

        $modulus  = self::base64UrlEncode((string) $details['rsa']['n']);
        $exponent = self::base64UrlEncode((string) $details['rsa']['e']);

        return [
            'kty' => 'RSA',
            'n'   => $modulus,
            'e'   => $exponent,
            'use' => 'sig',
            'alg' => 'RS256',
            'kid' => self::thumbprintOf($modulus, $exponent),
        ];
    }

    /**
     * RFC 7638 §3: the SHA-256 of the JWK's required members, in lexicographic order, with no
     * whitespace.
     */
    private static function thumbprintOf(string $modulus, string $exponent): string
    {
        $canonical = json_encode(
            ['e' => $exponent, 'kty' => 'RSA', 'n' => $modulus],
            JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES,
        );

        return self::base64UrlEncode(hash('sha256', $canonical, true));
    }

    private static function base64UrlEncode(string $value): string
    {
        return rtrim(strtr(base64_encode($value), '+/', '-_'), '=');
    }

    // --- Filesystem ---

    /**
     * @return array{0: string, 1: string} Private and public key, PEM encoded.
     */
    private function generate(): array
    {
        $key = openssl_pkey_new([
            'private_key_bits' => self::KEY_BITS,
            'private_key_type' => OPENSSL_KEYTYPE_RSA,
        ]);

        $details = $key === false ? false : openssl_pkey_get_details($key);

        if ($key === false || $details === false || !openssl_pkey_export($key, $private)) {
            throw new \RuntimeException(
                'Unable to generate an RSA keypair; check that ext-openssl is configured.',
                self::EXCEPTION_GENERATION_FAILED,
            );
        }

        return [$private, (string) $details['key']];
    }

    private function writePrivateKey(string $pem): void
    {
        $this->writeFile($this->configuration->privateKeyPath, $pem, self::PRIVATE_KEY_MODE);
    }

    private function writePublicKey(string $pem): void
    {
        $this->writeFile($this->configuration->publicKeyPath, $pem, self::PUBLIC_KEY_MODE);
    }

    /**
     * Written to a temporary file and renamed, so a reader never sees a half-written key, and
     * chmod'd BEFORE the rename, so a private key is never briefly world-readable.
     */
    private function writeFile(string $path, string $contents, int $mode): void
    {
        $directory = dirname($path);

        if (!is_dir($directory) && !mkdir($directory, 0700, true) && !is_dir($directory)) {
            throw new \RuntimeException(
                'Unable to create the key directory.',
                self::EXCEPTION_DIRECTORY_UNWRITABLE,
            );
        }

        Utils::protectDirectory($directory);

        $temporary = $path . '.' . bin2hex(random_bytes(6)) . '.tmp';

        if (file_put_contents($temporary, $contents) === false || !chmod($temporary, $mode) || !rename($temporary, $path)) {
            @unlink($temporary);

            throw new \RuntimeException(
                'Unable to write the key file.',
                self::EXCEPTION_DIRECTORY_UNWRITABLE,
            );
        }
    }

    private function read(string $path): string
    {
        $contents = @file_get_contents($path);

        if ($contents === false || $contents === '') {
            throw new \RuntimeException('Unable to read a key file.', self::EXCEPTION_KEY_UNREADABLE);
        }

        return $contents;
    }
}
